
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: chikalet
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chikalet"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      DB_URL: "postgresql://chikalet:root@db:5432/test?sslmode=disable"
      SECRET_KEY: "i_want_job"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: